name: main-build

#this drops to nuget

on:
  push:
    branches: [ main]
    paths-ignore:
      - 'templates/**'

  workflow_dispatch:

jobs:
  build:
    name: Build Comet-Nuget
    env:
        NUPKG_MAJOR: 0.2
        BASE: 334
    runs-on: windows-2022

    steps: 
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name:  install .NET 
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
          & .\dotnet-install.ps1 -Quality daily -Channel 6.0.2xx -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
          & dotnet --list-sdks     
              
      # - name: Install Visual Studio Preview
      #   shell: pwsh
      #   run: powershell .\build\install-vs.ps1
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
        
      # - name: Add MSBuild to Path
      #   shell: pwsh
      #   run: |
      #     dotnet tool update -g dotnet-vs
      #     & echo "$(vs where preview --prop=InstallationPath)\MSBuild\Current\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
    
      - name: Install and Run maui-check Tool
        shell: pwsh
        run: |
          & dotnet tool update --global redth.net.maui.check
          & maui-check --skip dotnet --verbose --non-interactive --fix --skip androidsdk --skip xcode --skip vswin --skip vsmac --skip edgewebview2
          
      - name: Install Maui Workload
        shell: pwsh
        run: |
          & dotnet workload install android ios maccatalyst tvos macos maui wasm-tools `
            --from-rollback-file https://aka.ms/dotnet/maui/preview.13.json  `
            --source https://aka.ms/dotnet6/nuget/index.json `
            --source https://api.nuget.org/v3/index.json

      - name: Restore Comet-net6-Nuget.sln
        run: msbuild /r build/Comet-net6-Nuget.sln
 
      - name: Build Comet-net6-Nuget.sln
        run: MSBuild build/Comet-net6-Nuget.sln
        
      - name: Nuget Pack step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=0.3.$MINOR_VERSION-beta
          echo "PACKAGE VERSION: $VERSION"
          nuget pack Comet.nuspec -version $VERSION -Symbols -SymbolPackageFormat snupkg

      # - name: Nuget Pack Template step
      #   shell: bash
      #   run: |
      #     MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
      #     VERSION=0.3.$MINOR_VERSION-beta
      #     echo "PACKAGE VERSION: $VERSION"
      #     nuget pack "templates\comet-templates.nuspec" -version $VERSION

      - uses: actions/upload-artifact@v2
        name: Upload Nuget Artifact
        with:
          name: nuget-artifact
          path: |
            **\*.nupkg
            **\*.snupkg
            **\*.symbols.nupkg
  
